# Generated by Django 2.1.1 on 2018-10-16 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='项目名称')),
                ('describe', models.TextField(default='', verbose_name='项目描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectDes_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectManager_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectName_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectNumber_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='startDate',
        ),
        migrations.AddField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='describe',
            field=models.TextField(default='', verbose_name='项目描述'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True, verbose_name='项目状态'),
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Project'),
        ),
    ]
