# Generated by Django 2.1.1 on 2018-11-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20181024_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Project', verbose_name='所属项目'),
        ),
    ]
